// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shop.data;

#nullable disable

namespace shop.data.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20250121125835_RemovedTransactions")]
    partial class RemovedTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("shop.domain.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BankDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("4c004c7a-aa08-4714-9f2a-153dce79154d"),
                            Age = 54,
                            BankDetails = "Capitec:5492875",
                            FirstName = "Harald",
                            LastName = "Berndt"
                        },
                        new
                        {
                            CustomerId = new Guid("95cdcf59-5d79-4fed-b5e5-771f9e7a2f30"),
                            Age = 32,
                            BankDetails = "Absa:475693",
                            FirstName = "Mauro",
                            LastName = "Lavista"
                        });
                });

            modelBuilder.Entity("shop.domain.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeCarted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeDelivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimePayed")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("7213d1a4-0da4-4d88-82eb-379cf1f4b03c"),
                            CustomerId = new Guid("4c004c7a-aa08-4714-9f2a-153dce79154d"),
                            OrderStatus = "InCart",
                            TimeCarted = new DateTime(2024, 4, 12, 5, 27, 19, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderId = new Guid("46e4fa2d-96bc-4c80-8ece-1a20cd7402b4"),
                            CustomerId = new Guid("4c004c7a-aa08-4714-9f2a-153dce79154d"),
                            OrderStatus = "Payed",
                            TimeCarted = new DateTime(2023, 5, 2, 23, 59, 23, 0, DateTimeKind.Unspecified),
                            TimePayed = new DateTime(2024, 2, 28, 17, 42, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderId = new Guid("ed5287a9-7240-4485-9f5f-392cd52f6ea7"),
                            CustomerId = new Guid("4c004c7a-aa08-4714-9f2a-153dce79154d"),
                            OrderStatus = "Delivered",
                            TimeCarted = new DateTime(2022, 6, 26, 19, 1, 34, 0, DateTimeKind.Unspecified),
                            TimeDelivered = new DateTime(2024, 8, 25, 16, 48, 42, 0, DateTimeKind.Unspecified),
                            TimePayed = new DateTime(2024, 5, 25, 21, 51, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderId = new Guid("22ed9b30-1d3c-4b96-ab3a-56f40608f2be"),
                            CustomerId = new Guid("4c004c7a-aa08-4714-9f2a-153dce79154d"),
                            OrderStatus = "InCart",
                            TimeCarted = new DateTime(2024, 11, 30, 23, 38, 55, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("shop.domain.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("4c004c7a-aa08-4714-9f2a-153dce79154d"),
                            InStock = 300,
                            Name = "tomatoes",
                            PictureName = "tomatoes.jpg",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = new Guid("571cffb5-45cf-4130-9fe8-db271cf7769e"),
                            InStock = 200,
                            Name = "potatoes",
                            PictureName = "potatoes.jpg",
                            Price = 10m
                        },
                        new
                        {
                            ProductId = new Guid("04a41261-0286-4532-9e78-9d65c77109f2"),
                            InStock = 70,
                            Name = "cabbages",
                            PictureName = "cabbages.jpg",
                            Price = 30m
                        },
                        new
                        {
                            ProductId = new Guid("6089c0d4-a700-48fb-bddd-e63e60c6c4fc"),
                            InStock = 100,
                            Name = "leeks",
                            PictureName = "leeks.jpg",
                            Price = 10m
                        },
                        new
                        {
                            ProductId = new Guid("57ac950f-8ca5-45d8-90c6-a9136752e844"),
                            InStock = 200,
                            Name = "carrots",
                            PictureName = "carrots.jpg",
                            Price = 7m
                        },
                        new
                        {
                            ProductId = new Guid("95cdcf59-5d79-4fed-b5e5-771f9e7a2f30"),
                            InStock = 150,
                            Name = "artichokes",
                            PictureName = "artichokes.jpg",
                            Price = 5m
                        },
                        new
                        {
                            ProductId = new Guid("885f5a71-8458-4c41-b437-a2b07153bf5d"),
                            InStock = 30,
                            Name = "beetroots",
                            PictureName = "beetroots.jpg",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = new Guid("8bf98d1e-78a2-44a5-ba3d-7e0e40079384"),
                            InStock = 250,
                            Name = "onions",
                            PictureName = "onions.jpg",
                            Price = 17m
                        },
                        new
                        {
                            ProductId = new Guid("3e7f899d-867c-4698-b853-6c66c0f413fb"),
                            InStock = 300,
                            Name = "maize",
                            PictureName = "maize.jpg",
                            Price = 15m
                        });
                });

            modelBuilder.Entity("shop.domain.ProductOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrderJoinTable");
                });

            modelBuilder.Entity("shop.domain.ProductProductSupplier", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MomentCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ProductId", "ProductSupplierId");

                    b.HasIndex("ProductSupplierId");

                    b.ToTable("ProductProductSuppliersJoinTable");
                });

            modelBuilder.Entity("shop.domain.ProductSupplier", b =>
                {
                    b.Property<Guid>("ProductSupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductSupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductSupplierId");

                    b.ToTable("ProductSuppliers");

                    b.HasData(
                        new
                        {
                            ProductSupplierId = new Guid("de5ae53e-886a-4061-8dfa-d5c2b27716ca"),
                            ProductSupplierName = "Juan"
                        },
                        new
                        {
                            ProductSupplierId = new Guid("32c81734-a0f9-45d2-b613-7a5304c1fb6f"),
                            ProductSupplierName = "John"
                        },
                        new
                        {
                            ProductSupplierId = new Guid("5f2601e2-2f25-4312-a61e-daa5be44a3fe"),
                            ProductSupplierName = "Johannes"
                        },
                        new
                        {
                            ProductSupplierId = new Guid("eca7177e-b329-4b1b-89cc-1f6ed6445fbe"),
                            ProductSupplierName = "Jean"
                        },
                        new
                        {
                            ProductSupplierId = new Guid("1ebd7129-aef3-4f96-8df9-4c035d214f27"),
                            ProductSupplierName = "Johan"
                        });
                });

            modelBuilder.Entity("shop.domain.Order", b =>
                {
                    b.HasOne("shop.domain.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("shop.domain.ProductOrder", b =>
                {
                    b.HasOne("shop.domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shop.domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("shop.domain.ProductProductSupplier", b =>
                {
                    b.HasOne("shop.domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shop.domain.ProductSupplier", null)
                        .WithMany()
                        .HasForeignKey("ProductSupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("shop.domain.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
